### ISSUE TITLE
permission needed in subdirectories

### ISSUE THREAD

**Issue by mkoo** [BNHM/CoreServices#1]
@JoyceGross -- same old issue of user (here it's pkahn) creating subfolders that then others cannot access

/web/amphibiaweb_disease and basically all its subdir (especially /assets where I need to upload images. (I have access to the main directory, just not any of the subdirs-- why no propagation?)

@jdeck88 @JoyceGross ideas to fix this general problem?

**Comment by JoyceGross** [comment]
Everyone needs to make sure files they create on annie and want others to edit are group-writable.

A couple of weeks ago I added this to your and Philip's .bashrc files
   # group read,write
   umask 002
so new files and directories you create on annie will by default be group-writable. But issues remain:

1) I did not change existing files/directories (they were not group-writable)
2) Philip might change the permissions back when he runs "git" the next time

Regarding #1, I just changed permissions on the existing directories/subdirectories with this command:
   find /usr/local/web/amphibiaweb_disease -type d -exec chmod 775 {} \;
and the existing files with this command:
   find /usr/local/web/amphibiaweb_disease -type f -exec chmod 664 {} \;

Regarding #2, it's possible my above fixes will be undone the next time git is run. I'm not sure, since I added "umask 002" and that may fix things. If not, you'll need to figure out how to run git without reverting the files to not being group-writable. 

If you google "git permissions on files" you'll see some useful info.

The other option is we all share the same account to edit these files, but that should not be necessary.

Joyce

**Comment by mkoo** [comment]
Tagging @tigerhawkvok for FYI
Thanks, Joyce! (just tested via ssh-ok now but not running git yet)
